DROP TABLE COMM_CODE;
CREATE TABLE COMM_CODE (
   COMM_CD CHAR(4) NOT NULL, 
   COMM_NM VARCHAR2(100) NOT NULL, 
   COMM_PARENT CHAR(4), 
   COMM_ORD NUMBER,
   CONSTRAINTS PK_COMM_CODE ON COMM_CODE (COMM_CD)
);

COMMENT ON TABLE COMM_CODE  IS '공통코드 테이블'
COMMENT ON COLUMN COMM_CODE.COMM_CD IS '코드'
COMMENT ON COLUMN COMM_CODE.COMM_NM IS '코드명'
COMMENT ON COLUMN COMM_CODE.COMM_PARENT IS '부모 코드'
COMMENT ON COLUMN COMM_CODE.COMM_ORD IS '순번'

Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB00','직업',null,0);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB01','주부','JB00',1);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB02','은행원','JB00',2);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB03','공무원','JB00',3);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB04','축산업','JB00',4);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB05','회사원','JB00',5);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB06','농업','JB00',6);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB07','자영업','JB00',7);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB08','학생','JB00',8);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB09','교사','JB00',9);

Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB00','취미',null,0);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB01','서예','HB00',1);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB02','장기','HB00',2);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB03','수영','HB00',3);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB04','독서','HB00',4);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB05','당구','HB00',5);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB06','바둑','HB00',6);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB07','볼링','HB00',7);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB08','스키','HB00',8);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB09','만화','HB00',9);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB10','낚시','HB00',10);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB11','영화감상','HB00',11);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB12','등산','HB00',12);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB13','개그','HB00',13);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB14','카레이싱','HB00',14);

Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC00','글분류',null,0);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC01','프로그램','BC00',1);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC02','웹','BC00',2);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC03','사는 이야기','BC00',3);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC04','취업','BC00',4);


